# Generated by Django 4.2.5 on 2023-10-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="selling_price",
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(blank=True, to="inventory.tag"),
        ),
    ]
